### ISSUE TITLE
Firebase update

### ISSUE THREAD

**Issue by RichardExpensys** [NeutrinosPlatform/cordova-plugin-ml-text#1]
Hi,

I have used this plugin and have found it excellent on both iOS and Android.

However recently a number of components required upgrading following a major update to the Firebase libraries and whilst the app now builds again the getText function produces an error ('Main Loop Exception').

I guess the main question is whether the plugin is being supported and likely to be updated?

many thanks in advance,

Richard

**Comment by ReallySmallSoftware** [comment]
I have recently updated a fork of this plugin to work with the latest version of Firebase on Android. I will be checking iOS soonish.

**Comment by JuneTwooo** [comment]
> I have recently updated a fork of this plugin to work with the latest version of Firebase on Android. I will be checking iOS soonish.

Can you share tour fork please ?

**Comment by ReallySmallSoftware** [comment]
Sure. Please see #2 where there is a link

**Comment by ChrisTomAlx** [comment]
[cordova-plugin-ml-text@2.0.0](https://www.npmjs.com/package/cordova-plugin-ml-text) is live. Closing this issue now. Please raise new issues if you guys run into any new problems. Also source is now hosted on GitHub.

Once again thanks to @ReallySmallSoftware for the PR. :))

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
