### ISSUE TITLE
ionic 2+ support

### ISSUE THREAD

**Issue by hpvaghani** [NeutrinosPlatform/cordova-plugin-ml-text#10]
Hi,

Please add ionic support for this plugin as installation/usage only shows cordova support only.

**Comment by ChrisTomAlx** [comment]
Hey @hpvaghani, 

I think the right place to ask for this would be on the ionic forums. But if you are able to do it yourself and raise a pr, it will be most welcome. I can test and merge it on my end.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
