### ISSUE TITLE
iOS build error: "Use of undeclared identifier 'MLKTextBlock'"

### ISSUE THREAD

**Issue by dragsirbu** [NeutrinosPlatform/cordova-plugin-ml-text#15]
Hi, I'm getting this error when I try to build for iOS:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/31959903/235710341-894b830b-8691-4d01-b5a7-eb93fc903616.png">

It used to work without any problem. I suspect that the error started appearing when I've updated to the latest version of cordova (11.1.0 in my case).

Env:
Cordova 11.1.0
Cordova iOS 6.1.1

**Comment by rpinto78** [comment]
Hi,

Solved by adding the following import to MLText.m.

`#import <MLKitTextRecognitionCommon/MLKitTextRecognitionCommon.h>`

<img width="872" alt="Screenshot 2023-05-03 at 11 08 47" src="https://user-images.githubusercontent.com/65413422/235889326-92b8055a-e6e0-451c-a262-a8833f4c3880.png">

What happened yesterday for this error to pop up?

**Comment by dragsirbu** [comment]
> 



> Hi,
> 
> Solved by adding the following import to MLText.m.
> 
> `#import <MLKitTextRecognitionCommon/MLKitTextRecognitionCommon.h>`
> 
> <img alt="Screenshot 2023-05-03 at 11 08 47" width="872" src="https://user-images.githubusercontent.com/65413422/235889326-92b8055a-e6e0-451c-a262-a8833f4c3880.png">
> 
> What happened yesterday for this error to pop up?

That worked. Thank you!

**Comment by megha2021** [comment]
> Hi,
> 
> Solved by adding the following import to MLText.m.
> 
> `#import <MLKitTextRecognitionCommon/MLKitTextRecognitionCommon.h>`
> 
> <img alt="Screenshot 2023-05-03 at 11 08 47" width="872" src="https://user-images.githubusercontent.com/65413422/235889326-92b8055a-e6e0-451c-a262-a8833f4c3880.png">
> 
> What happened yesterday for this error to pop up?

Hi, using the above import in my local machine I'm able to run successfully but when I'm trying to build in ionic Appflow(ionichub) the build fails. How can I resolve that
