### ISSUE TITLE
iOS Issues with UIWebView

### ISSUE THREAD

**Issue by TSomKes** [NeutrinosPlatform/cordova-plugin-ml-text#2]
I've been unable to get a Cordova iOS app accepted by Apple using this plugin.

When I add `cordova-plugin-ml-text` to the app (along with `cordova-plugin-firebasex`), Apple rejects the app with the notice `New apps that use UIWebView are no longer accepted`.

When I add _only_ `cordova-plugin-firebasex` to the app, and remove `cordova-plugin-ml-text`, Apple accepts the app with no UIWebView warning.  I suspect that the problem is with this particular plugin.

 Do you have any insight/advice?

**Comment by ChrisTomAlx** [comment]
@TSomKes 

Yea I have a feeling it must be an issue with this plugin as well. The ios google text detection plugin is a bit old and used some UIWebview elements. I have added these directly as frameworks to the plugin. I think a slight rework would be required. Change these frameworks to cocoapods and use the latest google text detection plugin. That should most likely solve the problem.. 

Although I am not entirely sure when I will be able to take a look at this. I would be grateful if you could raise a pr to overcome this. I wouldn't mind reviewing the pr and guiding you as required.

**Comment by ChrisTomAlx** [comment]
oops accidentally closed the issue

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by farazahmadvaival** [comment]
I am also facing the rejection from apple. Please update the repo with latest fixed to avoid any rejection.

Thanks

**Comment by ReallySmallSoftware** [comment]
I have recently updated a fork of this plugin to work with the latest version of Firebase on Android. I will be checking iOS soonish.

**Comment by thugic** [comment]
Any news on this?

**Comment by ReallySmallSoftware** [comment]
I have a version working on iOS, all updated to the latest libraries. Got a bit more testing to do and I can't categorically state that the UIWebView issue is addressed but I don't know why it wouldn't be. There is a slight loss of functionality with the latest on-device libraries - no languages or confidence scores are available.

**Comment by thugic** [comment]
Ok, are you willing to share that version with us? We'd be grateful :)

**Comment by ReallySmallSoftware** [comment]
Absolutely, it was always my intention to raise a PR. In the meantime, with absolutely no support (but comments very welcome) you can find the branch here:

https://bitbucket.org/trssc/cordova-plugin-ml-text/src/master/

**Comment by absoliman** [comment]
@ReallySmallSoftware  Why not creating a PR, if this change working properly @ChrisTomAlx what do you think

**Comment by ChrisTomAlx** [comment]
Yes that would be great if you could raise a PR. We have a lot of people here waiting for it maybe we could all test to see if anyone runs into any issues.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ReallySmallSoftware** [comment]
OK - PR raised I think. Let me know if you need anything else.

**Comment by ChrisTomAlx** [comment]
@ReallySmallSoftware  Really great work. Thanks for all the cleanup you did as well.
I have left a couple of comments. Would it be possible to make those changes and raise the pr to this repo on github? Since you removed all the large files I think we can move out of bitbucket

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ReallySmallSoftware** [comment]
OK. Done I think. I don't know if I've quite what you want regarding bitbucket > github, so sorry if that isn't quite right :-)

**Comment by absoliman** [comment]
@ChrisTomAlx I think you can close this bug and publish the plugin into npm in order to be able to install it via npm

Also, readme needs to be updated.

**Comment by ChrisTomAlx** [comment]
[cordova-plugin-ml-text@2.0.0](https://www.npmjs.com/package/cordova-plugin-ml-text) is live. Thanks a ton to @ReallySmallSoftware for the work.

Closing this issue now. Please raise new issues if you guys run into problems.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
