### ISSUE TITLE
Cannot find name 'mltext'. Did you mean 'Text'?ts(2552) lib.dom.d.ts(15438, 13): 'Text' is declared here.

### ISSUE THREAD

**Issue by indiascan** [NeutrinosPlatform/cordova-plugin-ml-text#4]
async recognizeImage(){

  //this.newcamera();
  navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true });

function onSuccess(imageData) {
      mltext.getText(onSuccess, onFail,{imgType : 0, imgSrc : imageData});
      // for imgType Use 0,1,2,3 or 4
      function onSuccess(recognizedText) {
            //var element = document.getElementById('pp');
            //element.innerHTML=recognizedText.blocks.blocktext;
            //Use above two lines to show recognizedText in html
            console.log(recognizedText);
            alert(recognizedText.blocks.blocktext);
      }
      function onFail(message) {
            alert('Failed because: ' + message);
      }
}
function onFail(message) {
      alert('Failed because: ' + message);
}

**Comment by ChrisTomAlx** [comment]
Make sure the plugin was added correctly. Try `cordova plugins` and sent the output here.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by indiascan** [comment]
cordova plugin add cordova-plugin-ml-text
Plugin "cordova-plugin-ml-text" already installed on android.
Plugin "cordova-plugin-ml-text" already installed on browser.
Adding cordova-plugin-ml-text to package.json

if you can update your documentation or readme because 
navigator.camera.getPicture() has been change now it's only camera.getPicture() and i am totally confused.
please help me out.
thanks in advance

**Comment by ChrisTomAlx** [comment]
If you are using ionic see the suggestion in #5 and also close this issue and lets continue the discussion there since I think its probably the same issue.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Refer #6 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
