### ISSUE TITLE
How can I use this plugin in ionic?

### ISSUE THREAD

**Issue by ceroideas** [NeutrinosPlatform/cordova-plugin-ml-text#5]
I have been using the cordova-plugin-mobile-ocr plugin, but I had to make a modification in the code and when trying to upload the application to the apple store, it was rejected by the UIWebView, I saw that it was on the same ionic page refers to this problem and at the end refers to this plugin ... My problem is that I do not know how to make it work in ionic.

When I write "cordova plugins" it appears as shown below, but I am unable to get it to work for me, can you help me?

![Screenshot_7](https://user-images.githubusercontent.com/49728029/96933430-b782a180-14c0-11eb-88d3-aa99a0919cf0.jpg)

Thank you very much in advance for the help

**Comment by ChrisTomAlx** [comment]
You can refer [this ](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/issues/17#issuecomment-395023179)and get an idea maybe. Its a different plugin but concept should be same. Instead of scan use mltext.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by elnezah** [comment]
I made as you describe in the link but I don't get the plugin to work. Maybe you can help me... please!

No matter how I try, I always get the same: `recognizedText` is `undefined`. This is my code:
```typescript
private performOCR(imgData: any): void {
        document.addEventListener("deviceready", () => {
            const ocrOptions = {imgType: 0, imgSrc: imgData};
            console.log(TestSandboxPage.TAG, 'deviceReady triggered', ocrOptions);
            mltext.getText(onSuccess, onFail, ocrOptions);

            function onSuccess(recognizedText) {
                console.log(TestSandboxPage.TAG, 'OCR success:', {recognizedText});
                alert(recognizedText.blocks.blocktext);
            }

            function onFail(message) {
                alert('Failed because: ' + message);
            }
        }, false);
    }
```
What I give as `imgData` is the result of the plugin camera with the same settings you have in the example [here](https://github.com/NeutrinosPlatform/cordova-plugin-ml-text#working-examples). So, as I call `performOCR` I get the following in the console:
`TestSandboxPage deviceReady triggered {imgType: 0, imgSrc: "file:///storage/emulated/0/Android/data/com.mycompany.myappname/cache/1605601905852.jpg"}` . I have also tried other combinations of `cameraOptions.destinationType` and `mltextOptions.imgType`, no success.

The thing is that `onSuccess` is never called: I placed there all kind of `console.logs` and they never show in the console. `onFaill` is also never called. I checked the existence of `mltext` (declared above `@Component`, as specified in the scan plugin issue), it seems to be there when needed, as a call with no parameters will trigger the expected alert pop-up.

Any help would be very appreciated.

**Comment by ChrisTomAlx** [comment]
Refer #6 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
