### ISSUE TITLE
Issue when building for iOS with SAP: fatal: could not create work tree dir 'cocoapods': Operation not permitted

### ISSUE THREAD

**Issue by MartinConradsen** [NeutrinosPlatform/cordova-plugin-ml-text#8]
Hi,

I've been struggling with this problem for quite a while now, and I simply can't find any documentation on the issue. I'm trying to make this plugin work with SAP Web IDE, of which I'm a fairly new user. I have no problems with using it on Android.

I've added this plugin as well as [cordova-plugin-cocoapod-supportx](https://www.npmjs.com/package/cordova-plugin-cocoapod-supportx) in an attempt to make this work on iOS. In my config.xml, I've added the following lines:

```
<preference name="pods_ios_min_version" value="8.0"/>
<preference name="pods_use_frameworks" value="true"/>
<pod name="MLKitTextRecognition"/>
```

When I try to build the project for iOS, however, I get the following build error:

```
Failed to install 'cordova-plugin-ml-text': Error: pod: Command failed with exit code 1 Error output:
fatal: could not create work tree dir 'cocoapods': Operation not permitted
    at ChildProcess.whenDone (*/cordova_iOS_6147d1016f3f431aa14e488b757da610/workspace/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
pod: Command failed with exit code 1 Error output:
fatal: could not create work tree dir 'cocoapods': Operation not permitted
```

I'm really just at an absolute loss, so I was wondering: do you have any idea of how to get past this issue?

Thanks in advance,
Martin

**Comment by ChrisTomAlx** [comment]
Hey @MartinConradsen 
This error seems to be a permission issue, since it tried to create a dir and the operation was not permitted.
Did you try testing with a local machine maybe and see if that works? (Just to understand what piece is breaking)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by MartinConradsen** [comment]
Hey Chris, thanks for getting back. I ended up abandoning the implementation of OCR on iOS, since Cocoapods and SAP UI5 have a very toxic and comlicated relationship. 
It's a great plugin though, and it works perfectly for Android even with SAP, so thank you for that!
I'm closing this issue :)
