### ISSUE TITLE
Update cocoapods source path

### ISSUE THREAD

**Issue by seamlink-aalves** [NeutrinosPlatform/cordova-plugin-ml-text#9]
Hi,

Thank you for your great plugin.

Could you update the source path of the CocoaPods to the CDN URL (https://cdn.cocoapods.org/) in the plugin.xml? The CDN is much faster.

Thank you

**Comment by ChrisTomAlx** [comment]
Thank you to [David](https://github.com/Davids89) for his pr. Closing this issue now.

Cheers
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
